FROM alpine:3.7

RUN apk --update add git nginx git-daemon fcgiwrap spawn-fcgi curl

RUN mkdir /run/nginx /var/log/git
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx /etc/nginx/conf.d/
COPY htpasswd /etc/nginx/htpasswd

# ensure that the nginx group can write here
RUN chmod g+w /var/run/fcgiwrap

RUN mkdir /etc/privatecerts/
COPY *.pem /etc/privatecerts/

# make our server-side repos
RUN mkdir -p /git/app1.git /git/app2.git /git/system.git && \
    cd /git/app1.git && git init --bare && \
    cd /git/app2.git && git init --bare && \
    cd /git/system.git && git init --bare

ENTRYPOINT []
CMD spawn-fcgi -M 2660 -g www-data -s /var/run/fcgiwrap/fcgiwrap.sock /usr/bin/fcgiwrap && nginx "-g daemon off;"

